apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: traceable
  name: traceable-config
data:
  server.port: "8080"
  management.server.port: "8081"
  spring.main.banner-mode: "off"
  spring.application.name: "traceable"
  spring.data.mongodb.host: traceable-db-mongodb
  spring.data.mongodb.port: "27017"
