apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: traceable
  name: traceable
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: traceable
